### ISSUE TITLE
 ModuleNotFoundError: No module named 'kivymd.label'

### ISSUE THREAD

**Issue by anooprana985** [HeaTTheatR/CreatorKivyProject#12]
I have included the kivymd github link on my .spec fiile.
Also when i run buildozer android debug it works perfectly.But the app crashes on android.Can someone help me solve this(I can also share some part of the code if one want)
My Kivymd App crashes on android with the error:
(Note:This is from logcat).
12-15 15:47:28.337 30519 30561 I python  : Traceback (most recent call last):
12-15 15:47:28.337 30519 30561 I python  :   File "/home/physics/Desktop/MANIFOLDER_2nd/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/lang/parser.py", line 471, in execute_directives
12-15 15:47:28.337 30519 30561 I python  : ModuleNotFoundError: No module named 'kivymd.label'
12-15 15:47:28.337 30519 30561 I python  : 
12-15 15:47:28.337 30519 30561 I python  : During handling of the above exception, another exception occurred:
12-15 15:47:28.337 30519 30561 I python  : 
12-15 15:47:28.337 30519 30561 I python  : Traceback (most recent call last):
12-15 15:47:28.337 30519 30561 I python  :   File "/home/physics/Desktop/MANIFOLDER_2nd/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/lang/parser.py", line 473, in execute_directives
12-15 15:47:28.337 30519 30561 I python  : ModuleNotFoundError: No module named 'kivymd.label'
12-15 15:47:28.338 30519 30561 I python  :  Traceback (most recent call last):
12-15 15:47:28.338 30439 30465 E CostSaveMode: cost save mode not available
12-15 15:47:28.338 30519 30561 I python  :    File "/home/physics/Desktop/MANIFOLDER_2nd/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/lang/parser.py", line 471, in execute_directives
12-15 15:47:28.339 30519 30561 I python  :  ModuleNotFoundError: No module named 'kivymd.label'
12-15 15:47:28.339 30519 30561 I python  :  
12-15 15:47:28.340 30519 30561 I python  :  During handling of the above exception, another exception occurred:
12-15 15:47:28.340 30519 30561 I python  :  
12-15 15:47:28.340 30519 30561 I python  :  Traceback (most recent call last):
12-15 15:47:28.340 30519 30561 I python  :    File "/home/physics/Desktop/MANIFOLDER_2nd/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivy/lang/parser.py", line 473, in execute_directives
12-15 15:47:28.341 30519 30561 I python  :  ModuleNotFoundError: No module named 'kivymd.label'

**Comment by anooprana985** [comment]
The solution is fro kivymd.uix.label import Label.
