### ISSUE TITLE
Can't Create Project: errro KivyMD library not installed!

### ISSUE THREAD

**Issue by homdx** [HeaTTheatR/CreatorKivyProject#3]
Can't create empty project with:
`python main.py name_project version_project your_copyright path_to_project -repo repo_project_on_github -author name_author -mail mail_author -site site_project`

Error:
[ERROR  ] KivyMD library not installed!
```
(venv3) [user@user CreatorKivyProject]$ LANG=C python main.py name_project version_project your_copyright path_to_project -repo repo_project_on_github -author name_author -mail mail_author -site site_project
[INFO   ] [Logger      ] Record log in /home/user/.kivy/logs/kivy_19-01-10_4.txt
[INFO   ] [Kivy        ] v1.10.1
[INFO   ] [Python      ] v3.6.7 (default, Nov 23 2018, 12:11:28) 
[GCC 8.2.1 20181105 (Red Hat 8.2.1-5)]
[INFO   ] [Creator Kivy Project version] 2.3.0
[INFO   ] Created project directory path_to_project/name_project ...
[INFO   ] Create entry point main.py ...
[INFO   ] Create file README.md ...
[INFO   ] Creating a code file program.py ...
[INFO   ] Creating a Makefile to compile language localization files ...
[INFO   ] Creating a license file ...
[INFO   ] Copying files project...
/home/user/Android/CreatorKivyProject/libs
path_to_project/name_project/libs
        path_to_project/name_project/libs/__init__.py
        path_to_project/name_project/libs/translation.py

path_to_project/name_project/libs/applibs
        path_to_project/name_project/libs/applibs/__init__.py

path_to_project/name_project/libs/applibs/bugreporter
        path_to_project/name_project/libs/applibs/bugreporter/__init__.py
        path_to_project/name_project/libs/applibs/bugreporter/README.md
        path_to_project/name_project/libs/applibs/bugreporter/LICENSE
        path_to_project/name_project/libs/applibs/bugreporter/bugreporter.py
        path_to_project/name_project/libs/applibs/bugreporter/Screenshot.png

path_to_project/name_project/libs/applibs/dialogs
        path_to_project/name_project/libs/applibs/dialogs/__init__.py
        path_to_project/name_project/libs/applibs/dialogs/README.md
        path_to_project/name_project/libs/applibs/dialogs/dialogs.py
        path_to_project/name_project/libs/applibs/dialogs/LICENSE
        path_to_project/name_project/libs/applibs/dialogs/selection.py
        path_to_project/name_project/libs/applibs/dialogs/Screenshot.png

path_to_project/name_project/libs/uix
        path_to_project/name_project/libs/uix/__init__.py
        path_to_project/name_project/libs/uix/navigationdrawer.py
        path_to_project/name_project/libs/uix/lists.py

path_to_project/name_project/libs/uix/baseclass
        path_to_project/name_project/libs/uix/baseclass/license.py
        path_to_project/name_project/libs/uix/baseclass/navdrawer.py
        path_to_project/name_project/libs/uix/baseclass/__init__.py
        path_to_project/name_project/libs/uix/baseclass/startscreen.py
        path_to_project/name_project/libs/uix/baseclass/about.py
        path_to_project/name_project/libs/uix/baseclass/basescreen.py

path_to_project/name_project/libs/uix/kv
        path_to_project/name_project/libs/uix/kv/about.kv
        path_to_project/name_project/libs/uix/kv/license.kv
        path_to_project/name_project/libs/uix/kv/basescreen.kv
        path_to_project/name_project/libs/uix/kv/startscreen.kv

/home/user/Android/CreatorKivyProject/data
path_to_project/name_project/data

path_to_project/name_project/data/locales
        path_to_project/name_project/data/locales/locales.txt

path_to_project/name_project/data/locales/po
        path_to_project/name_project/data/locales/po/README.rst
        path_to_project/name_project/data/locales/po/en.po
        path_to_project/name_project/data/locales/po/ru.po

path_to_project/name_project/data/locales/en

path_to_project/name_project/data/locales/en/LC_MESSAGES
        path_to_project/name_project/data/locales/en/LC_MESSAGES/Ttest.mo

path_to_project/name_project/data/locales/ru

path_to_project/name_project/data/locales/ru/LC_MESSAGES
        path_to_project/name_project/data/locales/ru/LC_MESSAGES/Ttest.mo

path_to_project/name_project/data/images
        path_to_project/name_project/data/images/icon.png
        path_to_project/name_project/data/images/open-source-logo.png
        path_to_project/name_project/data/images/navigation_bg.png

/home/user/Android/CreatorKivyProject/test
[INFO   ] Create file navdrawer.kv ...
[INFO   ] Installing the KivyMD library ...
Cloning into 'KivyMD'...
remote: Enumerating objects: 134, done.
remote: Counting objects: 100% (134/134), done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 2365 (delta 71), reused 106 (delta 47), pack-reused 2231
Receiving objects: 100% (2365/2365), 144.43 MiB | 857.00 KiB/s, done.
Resolving deltas: 100% (1351/1351), done.
[ERROR  ] KivyMD library not installed!
(venv3) [user@user CreatorKivyProject]$ 
```
Python 3.6.7
Kivy             1.10.1

**Comment by HeaTTheatR** [comment]
@homdx Try **sudo python main.py ...**

**Comment by homdx** [comment]
As you could see in the log: **(venv3)** I use a virtual environment
Why then is it me, if you propose to setup the package in the main system :(

**Comment by kristoffer-paulsson** [comment]
Maybe this is the same:

 Traceback (most recent call last):
   File "/Users/<user>/Documents/Repositories/logo/Logo/libs/applibs/bugreporter/bugreporter.py", line 14, in <module>
     from kivymd.button import MDFlatButton
 ModuleNotFoundError: No module named 'kivymd.button'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/Users/<user>/Documents/Repositories/logo/Logo/main.py", line 40, in <module>
     from bugreporter import BugReporter
   File "/Users/<user>/Documents/Repositories/logo/Logo/libs/applibs/bugreporter/__init__.py", line 17, in <module>
     from . bugreporter import BugReporter
   File "/Users/<user>/Documents/Repositories/logo/Logo/libs/applibs/bugreporter/bugreporter.py", line 16, in <module>
     raise ImportError('Install package KivyMD')
 ImportError: Install package KivyMD
None

Should be: from kivymd.uix.button import MDFlatButton
but is: from kivymd.button import MDFlatButton

**Comment by HeaTTheatR** [comment]
This project is not developing ...
